#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+ Listens on port 80.
#+ Returns a page containing "Hello World" when quried
#+     at the root with a curl GET request.
#+    Configures /redirect_me as a "301 Moved Permanently".
#+    Includes a custom 404 page containing "Ceci n'est pas une page".
#+    Contains a custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.


# Update package list
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Ensure nginx is running
sudo service nginx start


# Create a basic HTML file with "Hello World"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# http reponse header
sudo sed -i"/location \/ {/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

service nginx restart

# Confirm Nginx is listening on port 80
LISTENING=$(sudo netstat -tuln | grep ':80 ')
if [ -z "$LISTENING" ];
then
        echo "Nginx is not listening on port 80";
        exit;
else
        echo "Nginx is listening on port 80."
fi

# Restart nginx without systemctl
sudo kill -s HUP $(cat /var/run/nginx.pid)

echo "Nginx configured successfuly."
