#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend haproxy_balancer
        bind :80
        mode http
        default_backend webservers

backend webservers
        balance roundrobin
        server 360823-web-01 54.236.30.33:80
        server 360823-web-02 52.91.132.222:80
"
# Update packages
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Test syntax errors
sudo nginx -t

# Restarts HAproxy service
sudo service haproxy restart
