#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it

mysqldump --all-databases -uroot -p="$1" > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" backup.sql
