#!/usr/bin/env bash
# This script tells a story based on the contents of the '/etc/passwd' file

filename="/etc/passwd"
f1=""
f2=""
f3=""
while IFS= read -r line
do
	IFS=':' read -r f1 f2 f3 f4 f5 f6 f7 <<< "$line"
	
	# Use the username (f1) if GECOS field (f5) is empty
	user_info=${f5: +"${f5}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"}
	echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f4}. ${user_info: -${f1}}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"
done < "$filename"
